yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    )
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/article.html
{% load thumbnail %}
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }} 
      <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d M Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>
  {{ post.text|safe }}
  </p>
  <a href="{% url 'posts:post' post.pk %}">подробная информация </a>
</article>      

yatube/templates/includes/comments.html
{% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}

yatube/templates/includes/error_check.html
{% if form.errors %}
    {% for field in form %} 
        {% for error in field.errors %}            
            <div class="alert alert-danger">
            {{ error|escape }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
        {{ error|escape }}
        </div>
    {% endfor %}
{% endif %}

yatube/templates/includes/field_view.html
{% load user_filters %}
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
  {% csrf_token %} 
  {% for field in form %}
    <div class="form-group row my-3 py-3">
      <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
      </label>
      {{ field|addclass:'form-control' }} 
      {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
        {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  {% endfor %}

yatube/templates/includes/footer.html
<p>© {% now "Y" %} Copyright <span style="color:red">Ya</span>tube</p>  

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    <ul class="nav nav-pills">
      <li class="nav-item"> 
        <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item"> 
        <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link {% if view_name == 'users:password_change' %}active{% endif %} link-light" href="{% url 'users:password_change' %}">Изменить пароль</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link {% if view_name == 'users:logout' %}active{% endif %} link-light" href="{% url 'users:logout' %}">Выйти</a>
      </li>
      <li>
        Пользователь: {{ user.username }}
      </li>
      {% else %}
      <li class="nav-item"> 
        <a class="nav-link {% if view_name == 'users:login' %}active{% endif %} link-light" href="{% url 'users:login' %}">Войти</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link {% if view_name == 'users:signup' %}{% endif %} link-light" href="{% url 'users:signup' %}">Регистрация</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endwith %}