yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/users/urls.py
import django.contrib.auth.views as dj_views
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path(
        'logout/',
        dj_views.LogoutView.as_view(
            template_name='users/logged_out.html'
        ),
        name='logout'
    ),
    path(
        'signup/',
        views.SingUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        dj_views.LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset/',
        dj_views.PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset'),
    path(
        'password_reset/done/',
        dj_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>',
        dj_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='reset_confirm'
    ),
    path(
        'reset/done/',
        dj_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='reset_complete'
    ),
    path(
        'password_change/',
        dj_views.PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        dj_views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SingUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name: str = 'users/signup.html'

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> 
    </div> 
  </div> 
</div> 
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}Войти{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          <form method="post"
          {% include 'includes/error_check.html' %}
          {% include 'includes/field_view.html' %}        
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> 
      </div> 
    </div> 
</div> 
{% endblock %} 

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}
  Пароль изменён
{% endblock title %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Пароль изменён
        </div>
        <div class="card-body"> 
          <p>Пароль изменён успешно</p>
        </div> <!-- card body -->
        <a style="text-align: center;" href="{% url 'users:login' %}">
          вернуться на страницу авторизации
        </a><br><br>      
      </div> 
    </div> 
  </div> 
</div>

{% endblock content %}

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block title %}
  Изменение пароля
{% endblock title %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Изменить пароль
          </div>
          <div class="card-body">
            <form method="post"
            {% include 'includes/error_check.html' %}
            {% include 'includes/field_view.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}
  Сброс пароля прошёл успешно
{% endblock title %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Восстановление пароля завершено
          </div>
          <div class="card-body">
            <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="{% url 'users:login' %}">войти</a>
          </div> 
        </div> 
      </div>
    </div> 
  </div
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}
  Новый пароль
{% endblock title %}
{% block content %}
{% if validlink %}
<div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Введите новый пароль
          </div>
          <div class="card-body">
            {% include 'includes/error_check.html' %}  
            <form method="post"
              {% include 'icludes/field_view.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Назначить новый пароль
                </button>
              </div>
            </form>
          </div> 
        </div> 
      </div> 
    </div> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Ошибка
          </div>
          <div class="card-body">
            <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
          </div> 
        </div> 
      </div> 
    </div> 
  </div>
{% endif %}
{% endblock content %}

yatube/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %}
  Сброс прошёл успешно
{% endblock title %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Отправлено письмо
          </div>
          <div class="card-body">
            <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
          </div> 
        </div> 
      </div>
    </div> 
  </div>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}Сброс пароля{% endblock title %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-12 p-5">
      <div class="card">
        <div class="card-header">
        Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
        </div>
        {% include 'includes/error_check.html' %}
        <div class="card-body"> 
          <form method="post"
            {% if action_url %}
            action="{% url action_url %}"
            {% endif %}>
            {% include 'includes/field_view.html' %} 
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
              Сбросить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>  
</div>
{% endblock content %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
              {% include 'includes/error_check.html' %}
              <form method="post"
                {% if action_url %}
                action="{% url action_url %}"
                {% endif %} >
              {% include 'includes/field_view.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div> 
      </div> 
  </div> 
{% endblock %}